[2020-07-13 16:17:10,180] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-07-13 16:17:37,998] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-07-13 16:18:19,257] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /Users/yangxiaotong/svn/TIP_toolkit/quality_inspection/python-workspace/project_ipmitool/project_ipmitool/settings.py changed, reloading.
[2020-07-13 16:18:19,835] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-07-13 16:18:38,323] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /Users/yangxiaotong/svn/TIP_toolkit/quality_inspection/python-workspace/project_ipmitool/project_ipmitool/settings.py changed, reloading.
[2020-07-13 16:18:38,725] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-07-13 16:25:32,072] [log.py:222] [log:log_response] [WARNING]- Not Found: /ipmitool/api/ipmi
[2020-07-13 16:25:32,074] [log.py:222] [log:log_response] [WARNING]- Not Found: /ipmitool/api/ipmi
[2020-07-13 16:25:32,075] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /ipmitool/api/ipmi HTTP/1.1" 404 2017
[2020-07-13 16:25:32,075] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /ipmitool/api/ipmi HTTP/1.1" 404 2017
[2020-07-13 16:25:59,013] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /Users/yangxiaotong/svn/TIP_toolkit/quality_inspection/python-workspace/project_ipmitool/project_ipmitool/urls.py changed, reloading.
[2020-07-13 16:25:59,642] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-07-13 16:26:14,683] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ipmitool/api/ipmi/
Traceback (most recent call last):
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 419, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[2020-07-13 16:26:14,685] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ipmitool/api/ipmi/
Traceback (most recent call last):
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 419, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[2020-07-13 16:26:14,687] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /ipmitool/api/ipmi/ HTTP/1.1" 500 81819
[2020-07-13 16:26:14,688] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /ipmitool/api/ipmi/ HTTP/1.1" 500 81842
[2020-07-13 16:40:52,991] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /Users/yangxiaotong/svn/TIP_toolkit/quality_inspection/python-workspace/project_ipmitool/ipmitool/views.py changed, reloading.
[2020-07-13 16:40:53,642] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-07-13 16:44:04,098] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ipmitool/api/ipmi/
Traceback (most recent call last):
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 419, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[2020-07-13 16:44:04,100] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ipmitool/api/ipmi/
Traceback (most recent call last):
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 419, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[2020-07-13 16:44:04,101] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /ipmitool/api/ipmi/ HTTP/1.1" 500 81819
[2020-07-13 16:44:04,102] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /ipmitool/api/ipmi/ HTTP/1.1" 500 81842
[2020-07-13 17:02:48,941] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /Users/yangxiaotong/svn/TIP_toolkit/quality_inspection/python-workspace/project_ipmitool/ipmitool/views.py changed, reloading.
[2020-07-13 17:02:49,498] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-07-13 17:43:17,980] [log.py:222] [log:log_response] [WARNING]- Not Found: /ipmitool/api/ipmitool/
[2020-07-13 17:43:17,981] [log.py:222] [log:log_response] [WARNING]- Not Found: /ipmitool/api/ipmitool/
[2020-07-13 17:43:17,983] [log.py:222] [log:log_response] [WARNING]- Not Found: /ipmitool/api/ipmitool/
[2020-07-13 17:43:17,985] [log.py:222] [log:log_response] [WARNING]- Not Found: /ipmitool/api/ipmitool/
[2020-07-13 17:43:17,986] [log.py:222] [log:log_response] [WARNING]- Not Found: /ipmitool/api/ipmitool/
[2020-07-13 17:43:17,989] [log.py:222] [log:log_response] [WARNING]- Not Found: /ipmitool/api/ipmitool/
[2020-07-13 17:43:17,991] [log.py:222] [log:log_response] [WARNING]- Not Found: /ipmitool/api/ipmitool/
[2020-07-13 17:43:17,993] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /ipmitool/api/ipmitool/ HTTP/1.1" 404 2028
[2020-07-13 17:43:17,994] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /ipmitool/api/ipmitool/ HTTP/1.1" 404 2028
[2020-07-13 17:43:17,996] [log.py:222] [log:log_response] [WARNING]- Not Found: /ipmitool/api/ipmitool/
[2020-07-13 17:43:17,997] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /ipmitool/api/ipmitool/ HTTP/1.1" 404 2028
[2020-07-13 17:43:17,997] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /ipmitool/api/ipmitool/ HTTP/1.1" 404 2028
[2020-07-13 17:43:17,998] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /ipmitool/api/ipmitool/ HTTP/1.1" 404 2028
[2020-07-13 17:43:17,999] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /ipmitool/api/ipmitool/ HTTP/1.1" 404 2028
[2020-07-13 17:43:18,000] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /ipmitool/api/ipmitool/ HTTP/1.1" 404 2028
[2020-07-13 17:43:18,002] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /ipmitool/api/ipmitool/ HTTP/1.1" 404 2028
[2020-07-13 17:44:01,482] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /Users/yangxiaotong/svn/TIP_toolkit/quality_inspection/python-workspace/project_ipmitool/ipmitool/views.py changed, reloading.
[2020-07-13 17:44:01,952] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-07-13 17:44:07,940] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ipmitool/api/ipmi/
Traceback (most recent call last):
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 419, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[2020-07-13 17:44:07,968] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ipmitool/api/ipmi/
Traceback (most recent call last):
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 419, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[2020-07-13 17:44:07,970] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ipmitool/api/ipmi/
Traceback (most recent call last):
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 419, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[2020-07-13 17:44:07,976] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ipmitool/api/ipmi/
Traceback (most recent call last):
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 419, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[2020-07-13 17:44:07,978] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ipmitool/api/ipmi/
Traceback (most recent call last):
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 419, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[2020-07-13 17:44:07,983] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ipmitool/api/ipmi/
Traceback (most recent call last):
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 419, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[2020-07-13 17:44:07,986] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /ipmitool/api/ipmi/ HTTP/1.1" 500 80156
[2020-07-13 17:44:07,987] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /ipmitool/api/ipmi/ HTTP/1.1" 500 80156
[2020-07-13 17:44:07,987] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /ipmitool/api/ipmi/ HTTP/1.1" 500 80156
[2020-07-13 17:44:07,989] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /ipmitool/api/ipmi/ HTTP/1.1" 500 80156
[2020-07-13 17:44:07,990] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /ipmitool/api/ipmi/ HTTP/1.1" 500 80156
[2020-07-13 17:44:07,992] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /ipmitool/api/ipmi/ HTTP/1.1" 500 80156
[2020-07-13 17:45:30,275] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ipmitool/api/ipmi/
Traceback (most recent call last):
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 419, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[2020-07-13 17:45:30,311] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ipmitool/api/ipmi/
Traceback (most recent call last):
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 419, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[2020-07-13 17:45:30,332] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ipmitool/api/ipmi/
Traceback (most recent call last):
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/Users/yangxiaotong/.virtualenvs/django-test/lib/python3.8/site-packages/rest_framework/views.py", line 419, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[2020-07-13 17:45:30,334] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /ipmitool/api/ipmi/ HTTP/1.1" 500 80156
[2020-07-13 17:45:30,335] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /ipmitool/api/ipmi/ HTTP/1.1" 500 80156
[2020-07-13 17:45:30,336] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /ipmitool/api/ipmi/ HTTP/1.1" 500 80156
[2020-07-13 17:49:54,181] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /Users/yangxiaotong/svn/TIP_toolkit/quality_inspection/python-workspace/project_ipmitool/ipmitool/views.py changed, reloading.
[2020-07-13 17:49:54,639] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-07-13 17:50:03,783] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /Users/yangxiaotong/svn/TIP_toolkit/quality_inspection/python-workspace/project_ipmitool/ipmitool/views.py changed, reloading.
[2020-07-13 17:50:04,308] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-07-13 17:50:38,072] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /Users/yangxiaotong/svn/TIP_toolkit/quality_inspection/python-workspace/project_ipmitool/ipmitool/views.py changed, reloading.
[2020-07-13 17:50:38,578] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-07-13 17:50:44,527] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /ipmitool/api/ipmi/ HTTP/1.1" 200 22
[2020-07-13 17:50:44,527] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /ipmitool/api/ipmi/ HTTP/1.1" 200 22
[2020-07-13 17:50:44,527] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /ipmitool/api/ipmi/ HTTP/1.1" 200 22
[2020-07-14 09:07:20,274] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /Users/yangxiaotong/svn/TIP_toolkit/quality_inspection/python-workspace/project_ipmitool/ipmitool/views.py changed, reloading.
