[2020-12-16 14:16:56,768] [log.py:222] [log:log_response] [WARNING]- Forbidden: /automation/api/script/
[2020-12-16 14:17:11,119] [log.py:222] [log:log_response] [WARNING]- Forbidden: /automation/api/script/
[2020-12-16 14:20:14,295] [log.py:222] [log:log_response] [WARNING]- Forbidden: /automation/api/script/
[2020-12-16 14:22:55,269] [log.py:222] [log:log_response] [WARNING]- Forbidden: /automation/api/script/
[2020-12-16 14:25:07,811] [log.py:222] [log:log_response] [WARNING]- Forbidden: /automation/api/script/
[2020-12-16 14:25:30,022] [log.py:222] [log:log_response] [WARNING]- Forbidden: /automation/api/script/
[2020-12-16 14:26:14,761] [log.py:222] [log:log_response] [WARNING]- Forbidden: /automation/api/script/
[2020-12-16 14:28:07,906] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-12-16 14:28:12,369] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-12-16 14:28:26,965] [log.py:222] [log:log_response] [WARNING]- Forbidden: /automation/api/script/
[2020-12-16 14:28:26,966] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /automation/api/script/?current_page=1&pre_page=10 HTTP/1.1" 403 31
[2020-12-16 14:31:44,975] [log.py:222] [log:log_response] [WARNING]- Forbidden: /automation/api/pxe_server/
[2020-12-16 14:31:44,975] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /automation/api/pxe_server/?current_page=1&pre_page=10&pxe_name=&pxe_server_ip= HTTP/1.1" 403 31
[2020-12-16 14:32:24,961] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-12-16 14:33:53,355] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-12-16 14:34:39,305] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-12-16 14:36:08,867] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-12-16 14:37:58,738] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-12-16 14:39:30,916] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-12-16 14:42:37,371] [log.py:222] [log:log_response] [WARNING]- Forbidden: /automation/api/script/
[2020-12-16 14:42:37,373] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /automation/api/script/?current_page=1&pre_page=10 HTTP/1.1" 403 31
[2020-12-16 14:42:56,566] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-12-16 14:47:13,073] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-12-16 14:47:21,591] [views.py:55] [views:authenticate] [INFO]- 200
[2020-12-16 14:47:21,736] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /automation/api/script/?current_page=1&pre_page=10 HTTP/1.1" 200 3183
[2020-12-16 14:47:43,062] [views.py:55] [views:authenticate] [INFO]- 200
[2020-12-16 14:47:43,150] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /automation/api/script/?current_page=1&pre_page=10 HTTP/1.1" 200 3183
[2020-12-16 15:21:31,650] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-12-16 15:22:32,445] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-12-16 15:22:55,590] [log.py:222] [log:log_response] [WARNING]- Forbidden: /automation/api/script/
[2020-12-16 15:22:55,591] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /automation/api/script/?current_page=1&pre_page=10 HTTP/1.1" 403 31
[2020-12-16 15:23:21,337] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-12-16 15:48:22,103] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-12-16 15:50:28,415] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ws/immediate_exec_script/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 122, in _wrapped_view
    result = middleware.process_request(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/dwebsocket/middleware.py", line 25, in process_request
    importlib.import_module(WEBSOCKET_FACTORY_CLASS[:offset]),
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/dwebsocket/backends/uwsgi/factory.py", line 1, in <module>
    import uwsgi
ModuleNotFoundError: No module named 'uwsgi'
[2020-12-16 15:51:50,356] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ws/immediate_exec_script/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 122, in _wrapped_view
    result = middleware.process_request(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/dwebsocket/middleware.py", line 25, in process_request
    importlib.import_module(WEBSOCKET_FACTORY_CLASS[:offset]),
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/dwebsocket/backends/uwsgi/factory.py", line 1, in <module>
    import uwsgi
ModuleNotFoundError: No module named 'uwsgi'
[2020-12-16 15:52:47,013] [views.py:564] [views:upload_immediate_exec_script] [INFO]- 开始连接10.10.10.130
[2020-12-16 15:52:47,781] [views.py:573] [views:upload_immediate_exec_script] [INFO]- 正在上传脚本文件到10.10.10.130
[2020-12-16 15:52:47,901] [views.py:577] [views:upload_immediate_exec_script] [INFO]- 脚本文件上传到10.10.10.130成功
[2020-12-16 15:52:47,902] [views.py:581] [views:upload_immediate_exec_script] [INFO]- 10.10.10.130正在执行脚本
[2020-12-16 15:52:51,084] [views.py:590] [views:upload_immediate_exec_script] [INFO]- 10.10.10.130脚本执行输出：Hello world!
[2020-12-16 15:52:52,086] [views.py:590] [views:upload_immediate_exec_script] [INFO]- 10.10.10.130脚本执行输出：this is a test script.....
[2020-12-16 15:52:53,088] [views.py:590] [views:upload_immediate_exec_script] [INFO]- 10.10.10.130脚本执行输出：script fimish.
[2020-12-16 15:52:54,090] [views.py:590] [views:upload_immediate_exec_script] [INFO]- 10.10.10.130脚本执行输出：the end.
[2020-12-16 15:56:01,943] [views.py:564] [views:upload_immediate_exec_script] [INFO]- 开始连接10.10.10.130
[2020-12-16 15:56:03,663] [views.py:573] [views:upload_immediate_exec_script] [INFO]- 正在上传脚本文件到10.10.10.130
[2020-12-16 15:56:03,862] [views.py:577] [views:upload_immediate_exec_script] [INFO]- 脚本文件上传到10.10.10.130成功
[2020-12-16 15:56:03,864] [views.py:581] [views:upload_immediate_exec_script] [INFO]- 10.10.10.130正在执行脚本
[2020-12-16 15:56:06,974] [views.py:590] [views:upload_immediate_exec_script] [INFO]- 10.10.10.130脚本执行输出：Hello world!
[2020-12-16 15:56:07,977] [views.py:590] [views:upload_immediate_exec_script] [INFO]- 10.10.10.130脚本执行输出：this is a test script.....
[2020-12-16 15:56:08,979] [views.py:590] [views:upload_immediate_exec_script] [INFO]- 10.10.10.130脚本执行输出：script fimish.
[2020-12-16 15:56:09,982] [views.py:590] [views:upload_immediate_exec_script] [INFO]- 10.10.10.130脚本执行输出：the end.
