*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec  8 14:05:08 2020] ***
compiled with version: 4.7.4 on 07 December 2020 02:52:42
os: Linux-4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018
nodename: rock-Inspiron-7472
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/rock/quality_inspection/python-workspace/project-automation
writing pidfile to /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.pid
detected binary path: /home/rock/anaconda3/envs/venv/bin/uwsgi
chdir() to /home/rock/quality_inspection/python-workspace/project-automation
your processes number limit is 31095
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8003 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:34495 (port auto-assigned) fd 3
Python version: 3.8.3 (default, May 19 2020, 18:47:26)  [GCC 7.3.0]
Python main interpreter initialized at 0xa54420
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 422160 bytes (412 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xa54420 pid: 16138 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 16138)
spawned uWSGI worker 1 (pid: 16143, cores: 2)
spawned uWSGI worker 2 (pid: 16146, cores: 2)
*** Stats server enabled on /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.status fd: 19 ***
spawned uWSGI http 1 (pid: 16148)
[pid: 16146|app: 0|req: 1/1] 127.0.0.1 () {46 vars in 839 bytes} [Tue Dec  8 14:05:25 2020] GET /automation/api/script/?current_page=1&pre_page=10 => generated 910 bytes in 455 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 0)
[pid: 16146|app: 0|req: 2/2] 127.0.0.1 () {46 vars in 867 bytes} [Tue Dec  8 14:05:32 2020] GET /automation/api/script_log/?log_use=0&current_page=1&pre_page=10 => generated 3470 bytes in 46 msecs (HTTP/1.1 200) 6 headers in 184 bytes (1 switches on core 1)
[2020-12-08 14:06:04,727] [views.py:460] [views:list] [INFO]- 已启动定时任务：[<Job (id=nm7lqswpjcg0000000 name=ScriptViewSet.task_thread)>]
[pid: 16146|app: 0|req: 3/3] 127.0.0.1 () {46 vars in 889 bytes} [Tue Dec  8 14:06:04 2020] GET /automation/api/script_timed_task/?name=&status=&current_page=1&pre_page=10 => generated 1137 bytes in 73 msecs (HTTP/1.1 200) 6 headers in 184 bytes (1 switches on core 0)
[pid: 16146|app: 0|req: 4/4] 127.0.0.1 () {46 vars in 867 bytes} [Tue Dec  8 14:06:14 2020] GET /automation/api/script_log/?log_use=0&current_page=1&pre_page=10 => generated 3470 bytes in 40 msecs (HTTP/1.1 200) 6 headers in 184 bytes (1 switches on core 1)
[pid: 16143|app: 0|req: 1/5] 127.0.0.1 () {46 vars in 839 bytes} [Tue Dec  8 14:06:18 2020] GET /automation/api/script/?current_page=1&pre_page=10 => generated 910 bytes in 281 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 0)
[pid: 16146|app: 0|req: 5/6] 127.0.0.1 () {46 vars in 797 bytes} [Tue Dec  8 14:06:23 2020] GET /automation/api/script/?use=0 => generated 839 bytes in 36 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 0)
[pid: 16143|app: 0|req: 2/7] 127.0.0.1 () {46 vars in 823 bytes} [Tue Dec  8 14:06:35 2020] GET /automation/api/script/?use=0&name=test.py => generated 446 bytes in 58 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 1)
Tue Dec  8 14:07:55 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Dec  8 14:07:55 2020 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Dec  8 14:07:55 2020 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Dec  8 14:07:55 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec  8 14:09:36 2020] ***
compiled with version: 4.7.4 on 07 December 2020 02:52:42
os: Linux-4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018
nodename: rock-Inspiron-7472
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/rock/quality_inspection/python-workspace/project-automation
writing pidfile to /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.pid
detected binary path: /home/rock/anaconda3/envs/venv/bin/uwsgi
chdir() to /home/rock/quality_inspection/python-workspace/project-automation
your processes number limit is 31095
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8003 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:44147 (port auto-assigned) fd 3
Python version: 3.8.3 (default, May 19 2020, 18:47:26)  [GCC 7.3.0]
Python main interpreter initialized at 0x228b420
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 422160 bytes (412 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x228b420 pid: 18663 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 18663)
spawned uWSGI worker 1 (pid: 18666, cores: 2)
spawned uWSGI worker 2 (pid: 18668, cores: 2)
*** Stats server enabled on /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.status fd: 19 ***
spawned uWSGI http 1 (pid: 18670)
[2020-12-08 14:09:43,417] [views.py:460] [views:list] [INFO]- 已启动定时任务：[<Job (id=nm7lqswpjcg0000000 name=ScriptViewSet.task_thread)>]
[pid: 18668|app: 0|req: 1/1] 127.0.0.1 () {46 vars in 889 bytes} [Tue Dec  8 14:09:43 2020] GET /automation/api/script_timed_task/?name=&status=&current_page=1&pre_page=10 => generated 1137 bytes in 314 msecs (HTTP/1.1 200) 6 headers in 184 bytes (1 switches on core 0)
[pid: 18666|app: 0|req: 1/2] 127.0.0.1 () {46 vars in 797 bytes} [Tue Dec  8 14:09:44 2020] GET /automation/api/script/?use=0 => generated 839 bytes in 296 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 0)
[pid: 18668|app: 0|req: 2/3] 127.0.0.1 () {46 vars in 827 bytes} [Tue Dec  8 14:09:48 2020] GET /automation/api/script/?use=0&name=test_1.sh => generated 394 bytes in 42 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 1)
[2020-12-08 14:11:44,209] [views.py:460] [views:list] [INFO]- 已启动定时任务：[<Job (id=nm7lqswpjcg0000000 name=ScriptViewSet.task_thread)>]
[pid: 18666|app: 0|req: 2/4] 127.0.0.1 () {46 vars in 889 bytes} [Tue Dec  8 14:11:44 2020] GET /automation/api/script_timed_task/?name=&status=&current_page=1&pre_page=10 => generated 1137 bytes in 89 msecs (HTTP/1.1 200) 6 headers in 184 bytes (1 switches on core 1)
[pid: 18666|app: 0|req: 3/5] 127.0.0.1 () {46 vars in 797 bytes} [Tue Dec  8 14:11:44 2020] GET /automation/api/script/?use=0 => generated 839 bytes in 36 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 0)
[pid: 18668|app: 0|req: 3/6] 127.0.0.1 () {46 vars in 823 bytes} [Tue Dec  8 14:11:52 2020] GET /automation/api/script/?use=0&name=test.py => generated 446 bytes in 40 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 0)
[pid: 18668|app: 0|req: 4/7] 127.0.0.1 () {46 vars in 839 bytes} [Tue Dec  8 14:13:50 2020] GET /automation/api/script/?current_page=1&pre_page=10 => generated 910 bytes in 40 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 1)
[pid: 18668|app: 0|req: 5/8] 127.0.0.1 () {46 vars in 797 bytes} [Tue Dec  8 14:13:53 2020] GET /automation/api/script/?use=0 => generated 839 bytes in 34 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 0)
[pid: 18668|app: 0|req: 6/9] 127.0.0.1 () {46 vars in 824 bytes} [Tue Dec  8 14:13:55 2020] GET /automation/api/script?use=0&name=test_1.sh => generated 0 bytes in 19 msecs (HTTP/1.1 301) 5 headers in 196 bytes (1 switches on core 1)
[pid: 18668|app: 0|req: 7/10] 127.0.0.1 () {46 vars in 826 bytes} [Tue Dec  8 14:13:55 2020] GET /automation/api/script/?use=0&name=test_1.sh => generated 394 bytes in 41 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 0)
[pid: 18668|app: 0|req: 8/11] 127.0.0.1 () {46 vars in 796 bytes} [Tue Dec  8 14:18:07 2020] GET /automation/api/script/?use=0 => generated 839 bytes in 35 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 1)
[pid: 18666|app: 0|req: 4/12] 127.0.0.1 () {46 vars in 821 bytes} [Tue Dec  8 14:18:19 2020] GET /automation/api/script?use=0&name=test.py => generated 0 bytes in 16 msecs (HTTP/1.1 301) 5 headers in 194 bytes (1 switches on core 1)
[pid: 18668|app: 0|req: 9/13] 127.0.0.1 () {46 vars in 823 bytes} [Tue Dec  8 14:18:19 2020] GET /automation/api/script/?use=0&name=test.py => generated 446 bytes in 38 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 1)
Tue Dec  8 14:19:31 2020 - ASYNC call without async mode !!!
[2020-12-08 14:19:32,286] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ws/immediate_exec_script/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "./script/views.py", line 531, in immediate_exec_script
    data = json.loads(str(data, encoding="utf-8"))
TypeError: decoding to str: need a bytes-like object, NoneType found
Tue Dec  8 14:19:32 2020 - uwsgi_response_writev_headers_and_body_do(): Bad file descriptor [core/writer.c line 306] during GET /ws/immediate_exec_script/ (127.0.0.1)
OSError: write error
[pid: 18668|app: 0|req: 10/14] 127.0.0.1 () {46 vars in 802 bytes} [Tue Dec  8 14:18:31 2020] GET /ws/immediate_exec_script/ => generated 0 bytes in 60608 msecs (HTTP/1.1 500) 7 headers in 0 bytes (0 switches on core 0)
Tue Dec  8 14:20:45 2020 - ASYNC call without async mode !!!
[2020-12-08 14:20:45,375] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ws/immediate_exec_script/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "./script/views.py", line 531, in immediate_exec_script
    data = json.loads(str(data, encoding="utf-8"))
TypeError: decoding to str: need a bytes-like object, NoneType found
Tue Dec  8 14:20:45 2020 - uwsgi_response_writev_headers_and_body_do(): Bad file descriptor [core/writer.c line 306] during GET /ws/immediate_exec_script/ (127.0.0.1)
OSError: write error
[pid: 18666|app: 0|req: 5/15] 127.0.0.1 () {46 vars in 802 bytes} [Tue Dec  8 14:19:45 2020] GET /ws/immediate_exec_script/ => generated 0 bytes in 60163 msecs (HTTP/1.1 500) 7 headers in 0 bytes (0 switches on core 0)
Tue Dec  8 14:45:16 2020 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Dec  8 14:45:16 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Dec  8 14:45:16 2020 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Dec  8 14:45:16 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec  8 14:46:22 2020] ***
compiled with version: 4.7.4 on 07 December 2020 02:52:42
os: Linux-4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018
nodename: rock-Inspiron-7472
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/rock/quality_inspection/python-workspace/project-automation
writing pidfile to /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.pid
detected binary path: /home/rock/anaconda3/envs/venv/bin/uwsgi
chdir() to /home/rock/quality_inspection/python-workspace/project-automation
your processes number limit is 31095
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8003 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:34935 (port auto-assigned) fd 3
Python version: 3.8.3 (default, May 19 2020, 18:47:26)  [GCC 7.3.0]
Python main interpreter initialized at 0xbdc4e0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 422160 bytes (412 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 6 seconds on interpreter 0xbdc4e0 pid: 8815 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 8815)
spawned uWSGI worker 1 (pid: 8874, cores: 2)
spawned uWSGI worker 2 (pid: 8876, cores: 2)
*** Stats server enabled on /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.status fd: 19 ***
spawned uWSGI http 1 (pid: 8878)
[pid: 8876|app: 0|req: 1/1] 127.0.0.1 () {46 vars in 797 bytes} [Tue Dec  8 14:49:29 2020] GET /automation/api/script/?use=0 => generated 839 bytes in 5755 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 0)
[pid: 8874|app: 0|req: 1/2] 127.0.0.1 () {46 vars in 867 bytes} [Tue Dec  8 14:49:44 2020] GET /automation/api/script?use=0&scrip_type=Python%E8%84%9A%E6%9C%AC => generated 0 bytes in 284 msecs (HTTP/1.1 301) 5 headers in 217 bytes (1 switches on core 0)
[pid: 8874|app: 0|req: 2/3] 127.0.0.1 () {46 vars in 869 bytes} [Tue Dec  8 14:49:44 2020] GET /automation/api/script/?use=0&scrip_type=Python%E8%84%9A%E6%9C%AC => generated 446 bytes in 61 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 1)
[pid: 8876|app: 0|req: 2/4] 127.0.0.1 () {46 vars in 819 bytes} [Tue Dec  8 14:49:45 2020] GET /automation/api/script?use=0&name=test.py => generated 0 bytes in 23 msecs (HTTP/1.1 301) 5 headers in 194 bytes (1 switches on core 1)
[pid: 8876|app: 0|req: 3/5] 127.0.0.1 () {46 vars in 822 bytes} [Tue Dec  8 14:49:45 2020] GET /automation/api/script/?use=0&name=test.py => generated 446 bytes in 37 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 0)
Tue Dec  8 14:50:59 2020 - ASYNC call without async mode !!!
[2020-12-08 14:50:59,943] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ws/immediate_exec_script/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "./script/views.py", line 531, in immediate_exec_script
    data = json.loads(str(data, encoding="utf-8"))
TypeError: decoding to str: need a bytes-like object, NoneType found
Tue Dec  8 14:51:00 2020 - uwsgi_response_writev_headers_and_body_do(): Bad file descriptor [core/writer.c line 306] during GET /ws/immediate_exec_script/ (127.0.0.1)
OSError: write error
[pid: 8874|app: 0|req: 3/6] 127.0.0.1 () {46 vars in 802 bytes} [Tue Dec  8 14:49:58 2020] GET /ws/immediate_exec_script/ => generated 0 bytes in 61050 msecs (HTTP/1.1 500) 7 headers in 0 bytes (0 switches on core 0)
Tue Dec  8 15:44:05 2020 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Dec  8 15:44:05 2020 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Dec  8 15:44:05 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Dec  8 15:44:05 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec  8 15:45:09 2020] ***
compiled with version: 4.7.4 on 07 December 2020 02:52:42
os: Linux-4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018
nodename: rock-Inspiron-7472
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/rock/quality_inspection/python-workspace/project-automation
writing pidfile to /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.pid
detected binary path: /home/rock/anaconda3/envs/venv/bin/uwsgi
chdir() to /home/rock/quality_inspection/python-workspace/project-automation
your processes number limit is 31095
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
- async cores set to 30 - fd table size: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8003 fd 4
initializing 30 uGreen threads with stack size of 262144 (256 KB)
uwsgi socket 0 bound to TCP address 127.0.0.1:44471 (port auto-assigned) fd 3
Python version: 3.8.3 (default, May 19 2020, 18:47:26)  [GCC 7.3.0]
Python main interpreter initialized at 0x141d270
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 422160 bytes (412 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0x141d270 pid: 10952 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 10952)
spawned uWSGI worker 1 (pid: 11024, cores: 2)
spawned uWSGI worker 2 (pid: 11025, cores: 2)
*** Stats server enabled on /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.status fd: 19 ***
spawned uWSGI http 1 (pid: 11026)
[2020-12-08 15:45:20,712] [log.py:222] [log:log_response] [WARNING]- Forbidden: /automation/api/script/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 142, in __call__
    start_response(status, response_headers)
SystemError: you can call uwsgi api function only from the main callable
[pid: 11024|app: 0|req: 1/1] 127.0.0.1 () {46 vars in 797 bytes} [Tue Dec  8 15:45:18 2020] GET /automation/api/script/?use=0 => generated 0 bytes in 2495 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
[2020-12-08 15:45:29,172] [log.py:222] [log:log_response] [WARNING]- Forbidden: /automation/api/script/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 142, in __call__
    start_response(status, response_headers)
SystemError: you can call uwsgi api function only from the main callable
[pid: 11025|app: 0|req: 1/2] 127.0.0.1 () {46 vars in 796 bytes} [Tue Dec  8 15:45:28 2020] GET /automation/api/script/?use=0 => generated 0 bytes in 271 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Tue Dec  8 15:47:09 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Dec  8 15:47:09 2020 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec  8 15:47:28 2020] ***
compiled with version: 4.7.4 on 07 December 2020 02:52:42
os: Linux-4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018
nodename: rock-Inspiron-7472
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/rock/quality_inspection/python-workspace/project-automation
writing pidfile to /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.pid
detected binary path: /home/rock/anaconda3/envs/venv/bin/uwsgi
chdir() to /home/rock/quality_inspection/python-workspace/project-automation
your processes number limit is 31095
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
- async cores set to 30 - fd table size: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8003 fd 4
initializing 30 uGreen threads with stack size of 262144 (256 KB)
uwsgi socket 0 bound to TCP address 127.0.0.1:34097 (port auto-assigned) fd 3
Python version: 3.8.3 (default, May 19 2020, 18:47:26)  [GCC 7.3.0]
Python main interpreter initialized at 0x1afc260
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 422160 bytes (412 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1afc260 pid: 12331 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 12331)
spawned uWSGI worker 1 (pid: 12343, cores: 2)
spawned uWSGI worker 2 (pid: 12344, cores: 2)
*** Stats server enabled on /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.status fd: 19 ***
spawned uWSGI http 1 (pid: 12345)
[2020-12-08 15:47:57,965] [log.py:222] [log:log_response] [WARNING]- Forbidden: /automation/api/script/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 142, in __call__
    start_response(status, response_headers)
SystemError: you can call uwsgi api function only from the main callable
[pid: 12344|app: 0|req: 1/1] 127.0.0.1 () {46 vars in 797 bytes} [Tue Dec  8 15:47:57 2020] GET /automation/api/script/?use=0 => generated 0 bytes in 287 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Tue Dec  8 15:49:57 2020 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Dec  8 15:49:57 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec  8 15:50:32 2020] ***
compiled with version: 4.7.4 on 07 December 2020 02:52:42
os: Linux-4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018
nodename: rock-Inspiron-7472
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/rock/quality_inspection/python-workspace/project-automation
writing pidfile to /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.pid
detected binary path: /home/rock/anaconda3/envs/venv/bin/uwsgi
chdir() to /home/rock/quality_inspection/python-workspace/project-automation
your processes number limit is 31095
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
- async cores set to 30 - fd table size: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8003 fd 4
initializing 30 uGreen threads with stack size of 262144 (256 KB)
uwsgi socket 0 bound to TCP address 127.0.0.1:40165 (port auto-assigned) fd 3
Python version: 3.8.3 (default, May 19 2020, 18:47:26)  [GCC 7.3.0]
Python main interpreter initialized at 0x23b62c0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 422160 bytes (412 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x23b62c0 pid: 14317 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 14317)
spawned uWSGI worker 1 (pid: 14326, cores: 2)
spawned uWSGI worker 2 (pid: 14327, cores: 2)
*** Stats server enabled on /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.status fd: 19 ***
spawned uWSGI http 1 (pid: 14328)
[2020-12-08 15:50:38,476] [log.py:222] [log:log_response] [WARNING]- Forbidden: /automation/api/script/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 142, in __call__
    start_response(status, response_headers)
SystemError: you can call uwsgi api function only from the main callable
[pid: 14327|app: 0|req: 1/1] 127.0.0.1 () {46 vars in 797 bytes} [Tue Dec  8 15:50:38 2020] GET /automation/api/script/?use=0 => generated 0 bytes in 272 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Tue Dec  8 15:50:53 2020 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Dec  8 15:50:53 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec  8 15:56:10 2020] ***
compiled with version: 4.7.4 on 07 December 2020 02:52:42
os: Linux-4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018
nodename: rock-Inspiron-7472
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/rock/quality_inspection/python-workspace/project-automation
writing pidfile to /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.pid
detected binary path: /home/rock/anaconda3/envs/venv/bin/uwsgi
chdir() to /home/rock/quality_inspection/python-workspace/project-automation
your processes number limit is 31095
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8003 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:46737 (port auto-assigned) fd 3
Python version: 3.8.3 (default, May 19 2020, 18:47:26)  [GCC 7.3.0]
Python main interpreter initialized at 0x2566520
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 422160 bytes (412 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x2566520 pid: 17564 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 17564)
spawned uWSGI worker 1 (pid: 17576, cores: 2)
spawned uWSGI worker 2 (pid: 17578, cores: 2)
*** Stats server enabled on /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.status fd: 19 ***
spawned uWSGI http 1 (pid: 17580)
Error getting due jobs from job store 'default': Error 113 connecting to 10.230.13.44:6379. No route to host.
Error getting due jobs from job store 'default': Error 113 connecting to 10.230.13.44:6379. No route to host.
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec  8 15:57:45 2020] ***
compiled with version: 4.7.4 on 07 December 2020 02:52:42
os: Linux-4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018
nodename: rock-Inspiron-7472
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/rock/quality_inspection/python-workspace/project-automation
writing pidfile to /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.pid
detected binary path: /home/rock/anaconda3/envs/venv/bin/uwsgi
chdir() to /home/rock/quality_inspection/python-workspace/project-automation
your processes number limit is 31095
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (0.0.0.0:8003).
bind(): Address already in use [core/socket.c line 769]
[2020-12-08 15:57:59,898] [log.py:222] [log:log_response] [WARNING]- Forbidden: /automation/api/script/
[pid: 17578|app: 0|req: 1/1] 127.0.0.1 () {46 vars in 797 bytes} [Tue Dec  8 15:57:59 2020] GET /automation/api/script/?use=0 => generated 31 bytes in 273 msecs (HTTP/1.1 403) 6 headers in 189 bytes (1 switches on core 0)
[pid: 17578|app: 0|req: 2/2] 127.0.0.1 () {46 vars in 796 bytes} [Tue Dec  8 15:58:17 2020] GET /automation/api/script/?use=0 => generated 839 bytes in 59 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 1)
[pid: 17578|app: 0|req: 3/3] 127.0.0.1 () {46 vars in 825 bytes} [Tue Dec  8 15:58:21 2020] GET /automation/api/script?use=0&name=test_1.sh => generated 0 bytes in 31 msecs (HTTP/1.1 301) 5 headers in 196 bytes (1 switches on core 0)
[pid: 17576|app: 0|req: 1/4] 127.0.0.1 () {46 vars in 827 bytes} [Tue Dec  8 15:58:21 2020] GET /automation/api/script/?use=0&name=test_1.sh => generated 394 bytes in 300 msecs (HTTP/1.1 200) 6 headers in 183 bytes (1 switches on core 0)
Tue Dec  8 15:59:30 2020 - ASYNC call without async mode !!!
[2020-12-08 15:59:30,891] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /ws/immediate_exec_script/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/dwebsocket/decorators.py", line 16, in new_func
    response = func(request, *args, **kwargs)
  File "./script/views.py", line 531, in immediate_exec_script
    data = json.loads(str(data, encoding="utf-8"))
TypeError: decoding to str: need a bytes-like object, NoneType found
Tue Dec  8 15:59:30 2020 - uwsgi_response_writev_headers_and_body_do(): Bad file descriptor [core/writer.c line 306] during GET /ws/immediate_exec_script/ (127.0.0.1)
OSError: write error
[pid: 17576|app: 0|req: 2/5] 127.0.0.1 () {46 vars in 802 bytes} [Tue Dec  8 15:58:30 2020] GET /ws/immediate_exec_script/ => generated 0 bytes in 60405 msecs (HTTP/1.1 500) 7 headers in 0 bytes (0 switches on core 1)
Gracefully killing worker 1 (pid: 17576)...
Gracefully killing worker 2 (pid: 17578)...
gateway "uWSGI http 1" has been buried (pid: 17580)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 8 seconds
binary reloading uWSGI...
chdir() to /home/rock/quality_inspection/python-workspace/project-automation
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:46737)
running /home/rock/anaconda3/envs/venv/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.19.1 (64bit) on [Tue Dec  8 16:19:09 2020] ***
compiled with version: 4.7.4 on 07 December 2020 02:52:42
os: Linux-4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018
nodename: rock-Inspiron-7472
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/rock/quality_inspection/python-workspace/project-automation
detected binary path: /home/rock/anaconda3/envs/venv/bin/uwsgi
chdir() to /home/rock/quality_inspection/python-workspace/project-automation
your processes number limit is 31095
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8003 fd 5
uwsgi socket 0 bound to TCP address 127.0.0.1:35623 (port auto-assigned) fd 4
Python version: 3.8.3 (default, May 19 2020, 18:47:26)  [GCC 7.3.0]
Python main interpreter initialized at 0x215b300
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 422160 bytes (412 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x215b300 pid: 17564 (default app)
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 17564)
spawned uWSGI worker 1 (pid: 31121, cores: 2)
spawned uWSGI worker 2 (pid: 31123, cores: 2)
*** Stats server enabled on /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.status fd: 19 ***
spawned uWSGI http 1 (pid: 31125)
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Dec 14 11:39:28 2020] ***
compiled with version: 4.7.4 on 07 December 2020 02:52:42
os: Linux-4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018
nodename: rock-Inspiron-7472
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /home/rock/quality_inspection/python-workspace/project-automation
writing pidfile to /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.pid
detected binary path: /home/rock/anaconda3/envs/venv/bin/uwsgi
chdir() to /home/rock/quality_inspection/python-workspace/project-automation
your processes number limit is 31095
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
- async cores set to 30 - fd table size: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8003 fd 3
initializing 30 uGreen threads with stack size of 262144 (256 KB)
uwsgi socket 0 bound to UNIX address /home/rock/quality_inspection/python-workspace/project-automation/uwsgi_socket.sock fd 6
Python version: 3.8.3 (default, May 19 2020, 18:47:26)  [GCC 7.3.0]
Python main interpreter initialized at 0x1ce4410
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 422160 bytes (412 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x1ce4410 pid: 21861 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 21861)
spawned uWSGI worker 1 (pid: 21882, cores: 2)
spawned uWSGI worker 2 (pid: 21883, cores: 2)
*** Stats server enabled on /home/rock/quality_inspection/python-workspace/project-automation/uwsgi.status fd: 19 ***
spawned uWSGI http 1 (pid: 21884)
Mon Dec 14 11:40:14 2020 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Mon Dec 14 11:40:14 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
