[2020-06-05 09:19:52,039] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:23:27,355] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 09:23:27,439] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 09:23:29,044] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 09:23:29,126] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1177
[2020-06-05 09:23:35,258] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 09:23:35,298] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 380
[2020-06-05 09:29:24,818] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:29:25,190] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:29:51,540] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:29:51,904] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:30:10,998] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:30:11,354] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:31:19,000] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:31:19,366] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:32:27,505] [log.py:222] [log:log_response] [WARNING]- Forbidden: /user/
[2020-06-05 09:32:27,506] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /user/ HTTP/1.1" 403 40
[2020-06-05 09:32:45,364] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 130, in list
    user_list = User.objects.get_queryset().filter(username__icontains=user_name).order_by('id')
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1312, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1171, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[2020-06-05 09:32:45,366] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/ HTTP/1.1" 500 20478
[2020-06-05 09:33:02,748] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 130, in list
    user_list = User.objects.get_queryset().filter(username__icontains=user_name).order_by('id')
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1312, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1171, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[2020-06-05 09:33:02,749] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/ HTTP/1.1" 500 20478
[2020-06-05 09:34:31,670] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 130, in list
    user_list = User.objects.get_queryset().filter(username__icontains=user_name).order_by('id')
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1312, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1171, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[2020-06-05 09:34:31,671] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/ HTTP/1.1" 500 20478
[2020-06-05 09:34:52,910] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 130, in list
    user_list = User.objects.get_queryset().filter(username__icontains=user_name).order_by('id')
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1312, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1171, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[2020-06-05 09:34:52,911] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/ HTTP/1.1" 500 20478
[2020-06-05 09:36:27,160] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user HTTP/1.1" 301 0
[2020-06-05 09:36:27,186] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 130, in list
    user_list = User.objects.get_queryset().filter(username__icontains=user_name).order_by('id')
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1312, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1171, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[2020-06-05 09:36:27,187] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/ HTTP/1.1" 500 20522
[2020-06-05 09:37:22,338] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 130, in list
    user_list = User.objects.get_queryset().filter(username__icontains=user_name).order_by('id')
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1312, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1171, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[2020-06-05 09:37:22,338] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/ HTTP/1.1" 500 20478
[2020-06-05 09:37:59,298] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/ HTTP/1.1" 200 1106
[2020-06-05 09:38:09,519] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 130, in list
    user_list = User.objects.get_queryset().filter(username__icontains=user_name).order_by('id')
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1312, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1171, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[2020-06-05 09:38:09,520] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/ HTTP/1.1" 500 20478
[2020-06-05 09:38:22,804] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:38:23,229] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:38:23,692] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/ HTTP/1.1" 200 2139
[2020-06-05 09:38:49,634] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:38:50,002] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:38:59,126] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=admin HTTP/1.1" 301 0
[2020-06-05 09:38:59,140] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=admin HTTP/1.1" 200 188
[2020-06-05 09:39:07,176] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=ad HTTP/1.1" 301 0
[2020-06-05 09:39:07,186] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ad HTTP/1.1" 200 188
[2020-06-05 09:39:13,061] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=a HTTP/1.1" 301 0
[2020-06-05 09:39:13,075] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=a HTTP/1.1" 200 923
[2020-06-05 09:40:49,782] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:40:50,137] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:40:57,157] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=a HTTP/1.1" 301 0
[2020-06-05 09:40:57,194] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=a HTTP/1.1" 200 923
[2020-06-05 09:41:09,513] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=A HTTP/1.1" 301 0
[2020-06-05 09:41:09,522] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=A HTTP/1.1" 200 2
[2020-06-05 09:42:00,644] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:42:00,945] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:42:05,470] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=A HTTP/1.1" 301 0
[2020-06-05 09:42:05,484] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=A HTTP/1.1" 200 2
[2020-06-05 09:42:08,622] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=a HTTP/1.1" 301 0
[2020-06-05 09:42:08,632] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=a HTTP/1.1" 200 188
[2020-06-05 09:42:12,809] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=admin HTTP/1.1" 301 0
[2020-06-05 09:42:12,818] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=admin HTTP/1.1" 200 188
[2020-06-05 09:42:15,947] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=admin1 HTTP/1.1" 301 0
[2020-06-05 09:42:15,955] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=admin1 HTTP/1.1" 200 2
[2020-06-05 09:42:19,826] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=ad HTTP/1.1" 301 0
[2020-06-05 09:42:19,837] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ad HTTP/1.1" 200 188
[2020-06-05 09:42:47,168] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:42:47,498] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:42:51,167] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=ad HTTP/1.1" 301 0
[2020-06-05 09:42:51,176] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ad HTTP/1.1" 200 188
[2020-06-05 09:42:55,798] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=Ad HTTP/1.1" 301 0
[2020-06-05 09:42:55,806] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=Ad HTTP/1.1" 200 188
[2020-06-05 09:43:01,669] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=AdM HTTP/1.1" 301 0
[2020-06-05 09:43:01,679] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=AdM HTTP/1.1" 200 188
[2020-06-05 09:43:32,201] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=None HTTP/1.1" 301 0
[2020-06-05 09:43:32,211] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=None HTTP/1.1" 200 2
[2020-06-05 09:43:59,890] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user HTTP/1.1" 301 0
[2020-06-05 09:43:59,928] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 130, in list
    user_list = User.objects.get_queryset().filter(username__istartswith=user_name).order_by('id')
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1312, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1171, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[2020-06-05 09:43:59,929] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/ HTTP/1.1" 500 20524
[2020-06-05 09:44:19,458] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:44:19,815] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:44:22,948] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user HTTP/1.1" 301 0
[2020-06-05 09:44:22,987] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 130, in list
    user_list = User.objects.get_queryset().filter(username__istartswith=user_name)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1312, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1171, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[2020-06-05 09:44:22,988] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/ HTTP/1.1" 500 20509
[2020-06-05 09:46:11,767] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:46:12,083] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:46:15,500] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user HTTP/1.1" 301 0
[2020-06-05 09:46:15,511] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/ HTTP/1.1" 200 2139
[2020-06-05 09:46:29,167] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=ad HTTP/1.1" 301 0
[2020-06-05 09:46:29,186] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ad HTTP/1.1" 200 188
[2020-06-05 09:49:39,552] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:49:39,883] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:49:47,778] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user HTTP/1.1" 301 0
[2020-06-05 09:49:47,790] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/ HTTP/1.1" 200 2139
[2020-06-05 09:50:58,601] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:50:58,961] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:51:09,612] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user HTTP/1.1" 301 0
[2020-06-05 09:51:09,625] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/ HTTP/1.1" 200 2139
[2020-06-05 09:52:34,497] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:52:34,856] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:52:39,786] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user HTTP/1.1" 301 0
[2020-06-05 09:52:39,829] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 132, in list
    user_list = User.objects.get_queryset().filter(username__istartswith=user_name).order_by('id')
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1312, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1171, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[2020-06-05 09:52:39,830] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/ HTTP/1.1" 500 20524
[2020-06-05 09:53:45,131] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:53:45,478] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:53:49,297] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user HTTP/1.1" 301 0
[2020-06-05 09:53:49,337] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 132, in list
    user_list = User.objects.get_queryset().filter(username__istartswith=user_name).order_by('id')
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1351, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1378, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1312, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 1171, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[2020-06-05 09:53:49,338] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/ HTTP/1.1" 500 20524
[2020-06-05 09:54:13,979] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:54:14,359] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:54:18,167] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user HTTP/1.1" 301 0
[2020-06-05 09:54:18,181] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/ HTTP/1.1" 200 2139
[2020-06-05 09:55:12,182] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 09:55:12,550] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 09:55:16,682] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user HTTP/1.1" 301 0
[2020-06-05 09:55:16,690] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/ HTTP/1.1" 200 2139
[2020-06-05 09:55:36,039] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 09:55:36,063] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 09:55:42,359] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=1&pre_page=10&username=ad HTTP/1.1" 200 0
[2020-06-05 09:55:42,382] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10&username=ad HTTP/1.1" 200 0
[2020-06-05 09:55:42,434] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=ad HTTP/1.1" 200 259
[2020-06-05 09:55:46,789] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=1&pre_page=10&username=admin HTTP/1.1" 200 0
[2020-06-05 09:55:46,817] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10&username=admin HTTP/1.1" 200 0
[2020-06-05 09:55:46,927] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=admin HTTP/1.1" 200 259
[2020-06-05 09:55:49,981] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=1&pre_page=10&username=adm HTTP/1.1" 200 0
[2020-06-05 09:55:49,990] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?current_page=1&pre_page=10&username=adm HTTP/1.1" 301 0
[2020-06-05 09:55:50,043] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10&username=adm HTTP/1.1" 200 0
[2020-06-05 09:55:50,109] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=adm HTTP/1.1" 200 259
[2020-06-05 09:55:52,659] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 09:56:34,491] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 09:58:15,238] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 09:58:15,275] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1177
[2020-06-05 09:58:25,676] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 09:58:28,423] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=1&pre_page=10&username=aaa HTTP/1.1" 200 0
[2020-06-05 09:58:28,433] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?current_page=1&pre_page=10&username=aaa HTTP/1.1" 301 0
[2020-06-05 09:58:28,484] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10&username=aaa HTTP/1.1" 200 0
[2020-06-05 09:58:28,533] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=aaa HTTP/1.1" 200 73
[2020-06-05 09:58:32,008] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:01:53,612] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:11:46,315] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 10:11:46,356] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:12:01,865] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:15:30,805] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=15 HTTP/1.1" 200 0
[2020-06-05 10:15:30,856] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=15 HTTP/1.1" 200 2211
[2020-06-05 10:15:35,180] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=15 HTTP/1.1" 200 2211
[2020-06-05 10:15:57,482] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=5 HTTP/1.1" 200 0
[2020-06-05 10:15:57,541] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=5 HTTP/1.1" 200 968
[2020-06-05 10:19:40,250] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=5 HTTP/1.1" 200 968
[2020-06-05 10:20:09,396] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=2&pre_page=5 HTTP/1.1" 200 0
[2020-06-05 10:20:09,421] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=5 HTTP/1.1" 200 940
[2020-06-05 10:20:10,288] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=5 HTTP/1.1" 200 968
[2020-06-05 10:20:11,654] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=5 HTTP/1.1" 200 940
[2020-06-05 10:20:12,962] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=5 HTTP/1.1" 200 968
[2020-06-05 10:20:15,196] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=5 HTTP/1.1" 200 940
[2020-06-05 10:20:46,910] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:23:02,736] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 10:23:02,751] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 447
[2020-06-05 10:23:04,144] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 10:23:04,163] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:23:06,404] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 447
[2020-06-05 10:23:07,733] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:26:01,817] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:26:05,798] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 447
[2020-06-05 10:26:20,859] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:27:45,955] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:27:47,686] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:28:12,068] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:28:14,418] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:29:11,089] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:29:15,579] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 447
[2020-06-05 10:29:16,947] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:29:46,674] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 447
[2020-06-05 10:36:15,151] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 10:36:15,185] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:38:11,208] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 10:38:11,223] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 447
[2020-06-05 10:38:13,293] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:38:27,420] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 447
[2020-06-05 10:44:13,456] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 10:44:13,494] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1177
[2020-06-05 10:44:33,640] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/1/ HTTP/1.1" 200 0
[2020-06-05 10:44:33,855] [basehttp.py:157] [basehttp:log_message] [INFO]- "PUT /role/1/ HTTP/1.1" 200 475
[2020-06-05 10:46:27,850] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1183
[2020-06-05 10:49:54,763] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1183
[2020-06-05 10:52:42,013] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1183
[2020-06-05 10:52:54,507] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/ HTTP/1.1" 200 0
[2020-06-05 10:52:54,610] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 137
[2020-06-05 10:53:00,695] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1321
[2020-06-05 10:53:11,770] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 137
[2020-06-05 10:53:19,040] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1459
[2020-06-05 10:53:29,948] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 10:53:29,985] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:53:32,833] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 10:53:32,848] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 447
[2020-06-05 10:53:41,378] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=2&pre_page=10&username=erysudjg HTTP/1.1" 200 0
[2020-06-05 10:53:41,387] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?current_page=2&pre_page=10&username=erysudjg HTTP/1.1" 301 0
[2020-06-05 10:53:41,437] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=2&pre_page=10&username=erysudjg HTTP/1.1" 200 0
[2020-06-05 10:53:41,572] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 136, in list
    result = paginator.page(current_page)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 70, in page
    number = self.validate_number(number)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 52, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: 本页结果为空
[2020-06-05 10:53:41,574] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/?current_page=2&pre_page=10&username=erysudjg HTTP/1.1" 500 19948
[2020-06-05 10:53:44,783] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 136, in list
    result = paginator.page(current_page)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 70, in page
    number = self.validate_number(number)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 52, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: 本页结果为空
[2020-06-05 10:53:44,784] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/?current_page=2&pre_page=10&username=erysudjg HTTP/1.1" 500 19948
[2020-06-05 10:53:57,640] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 136, in list
    result = paginator.page(current_page)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 70, in page
    number = self.validate_number(number)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 52, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: 本页结果为空
[2020-06-05 10:53:57,641] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/?current_page=2&pre_page=10&username=erysudjg HTTP/1.1" 500 19948
[2020-06-05 10:54:22,761] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:54:26,121] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=1&pre_page=10&username=erysudjg HTTP/1.1" 200 0
[2020-06-05 10:54:26,129] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?current_page=1&pre_page=10&username=erysudjg HTTP/1.1" 301 0
[2020-06-05 10:54:26,175] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10&username=erysudjg HTTP/1.1" 200 0
[2020-06-05 10:54:26,231] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=erysudjg HTTP/1.1" 200 73
[2020-06-05 10:54:29,873] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 447
[2020-06-05 10:54:32,457] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 136, in list
    result = paginator.page(current_page)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 70, in page
    number = self.validate_number(number)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 52, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: 本页结果为空
[2020-06-05 10:54:32,458] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/?current_page=2&pre_page=10&username=erysudjg HTTP/1.1" 500 19948
[2020-06-05 10:55:17,795] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/ HTTP/1.1" 200 0
[2020-06-05 10:55:17,871] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 177
[2020-06-05 10:55:22,016] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 10:55:26,657] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 625
[2020-06-05 10:56:08,440] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=ass HTTP/1.1" 301 0
[2020-06-05 10:56:08,452] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ass HTTP/1.1" 200 2
[2020-06-05 10:56:49,683] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=ass&current_page=2&pre_page=10 HTTP/1.1" 301 0
[2020-06-05 10:56:49,712] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 136, in list
    result = paginator.page(current_page)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 70, in page
    number = self.validate_number(number)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 52, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: 本页结果为空
[2020-06-05 10:56:49,713] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/?username=ass&current_page=2&pre_page=10 HTTP/1.1" 500 19872
[2020-06-05 10:56:59,959] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=ass&current_page=1&pre_page=10 HTTP/1.1" 301 0
[2020-06-05 10:56:59,972] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ass&current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 10:57:21,988] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=ass&current_page=2&pre_page=10 HTTP/1.1" 301 0
[2020-06-05 10:57:22,011] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 136, in list
    result = paginator.page(current_page)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 70, in page
    number = self.validate_number(number)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 52, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: 本页结果为空
[2020-06-05 10:57:22,012] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/?username=ass&current_page=2&pre_page=10 HTTP/1.1" 500 19872
[2020-06-05 10:59:00,962] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?current_page=2&pre_page=10 HTTP/1.1" 301 0
[2020-06-05 10:59:00,973] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 625
[2020-06-05 10:59:17,920] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?current_page=2&pre_page=10&username=admin HTTP/1.1" 301 0
[2020-06-05 10:59:17,945] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 136, in list
    result = paginator.page(current_page)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 70, in page
    number = self.validate_number(number)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 52, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: 本页结果为空
[2020-06-05 10:59:17,946] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/?current_page=2&pre_page=10&username=admin HTTP/1.1" 500 19880
[2020-06-05 11:00:51,023] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 136, in list
    result = paginator.page(current_page)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 70, in page
    number = self.validate_number(number)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 52, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: 本页结果为空
[2020-06-05 11:00:51,024] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/?current_page=2&pre_page=10&username=admin HTTP/1.1" 500 19794
[2020-06-05 11:02:38,341] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 136, in list
    result = paginator.page(current_page)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 70, in page
    number = self.validate_number(number)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 52, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: 本页结果为空
[2020-06-05 11:02:38,341] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/?current_page=2&pre_page=3&username=admin HTTP/1.1" 500 19791
[2020-06-05 11:06:46,940] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:06:46,955] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:06:50,575] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=1&pre_page=10&username=a HTTP/1.1" 200 0
[2020-06-05 11:06:50,666] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10&username=a HTTP/1.1" 200 0
[2020-06-05 11:06:50,721] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=a HTTP/1.1" 200 259
[2020-06-05 11:06:52,211] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:06:52,224] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 625
[2020-06-05 11:06:53,830] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=2&pre_page=10&username=a HTTP/1.1" 200 0
[2020-06-05 11:06:53,838] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?current_page=2&pre_page=10&username=a HTTP/1.1" 301 0
[2020-06-05 11:06:53,885] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=2&pre_page=10&username=a HTTP/1.1" 200 0
[2020-06-05 11:06:53,963] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /user/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 136, in list
    result = paginator.page(current_page)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 70, in page
    number = self.validate_number(number)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/paginator.py", line 52, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: 本页结果为空
[2020-06-05 11:06:53,964] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /user/?current_page=2&pre_page=10&username=a HTTP/1.1" 500 19927
[2020-06-05 11:08:41,246] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:08:45,914] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=a HTTP/1.1" 200 259
[2020-06-05 11:08:47,907] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 625
[2020-06-05 11:08:49,568] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=a HTTP/1.1" 200 259
[2020-06-05 11:08:53,408] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 625
[2020-06-05 11:08:56,680] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:09:03,096] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=1&pre_page=10&username=ryph HTTP/1.1" 200 0
[2020-06-05 11:09:03,103] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?current_page=1&pre_page=10&username=ryph HTTP/1.1" 301 0
[2020-06-05 11:09:03,150] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10&username=ryph HTTP/1.1" 200 0
[2020-06-05 11:09:03,201] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=ryph HTTP/1.1" 200 73
[2020-06-05 11:09:11,498] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 625
[2020-06-05 11:09:19,507] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:09:55,497] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/ HTTP/1.1" 200 0
[2020-06-05 11:09:55,519] [log.py:222] [log:log_response] [WARNING]- Bad Request: /user/
[2020-06-05 11:09:55,519] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /user/ HTTP/1.1" 400 47
[2020-06-05 11:10:07,684] [log.py:222] [log:log_response] [WARNING]- Bad Request: /user/
[2020-06-05 11:10:07,686] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /user/ HTTP/1.1" 400 47
[2020-06-05 11:10:28,860] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 173
[2020-06-05 11:10:41,095] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 173
[2020-06-05 11:10:43,430] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 173
[2020-06-05 11:10:45,480] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 173
[2020-06-05 11:10:47,356] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 173
[2020-06-05 11:10:49,222] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 173
[2020-06-05 11:10:50,958] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 173
[2020-06-05 11:10:52,700] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 173
[2020-06-05 11:10:56,509] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:10:59,780] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 1843
[2020-06-05 11:11:04,118] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=3&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:11:04,126] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=3&pre_page=10 HTTP/1.1" 200 247
[2020-06-05 11:11:08,964] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=1&pre_page=10&username=ey HTTP/1.1" 200 0
[2020-06-05 11:11:08,972] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?current_page=1&pre_page=10&username=ey HTTP/1.1" 301 0
[2020-06-05 11:11:09,020] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10&username=ey HTTP/1.1" 200 0
[2020-06-05 11:11:09,080] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=ey HTTP/1.1" 200 1803
[2020-06-05 11:11:20,108] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:11:22,532] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 1843
[2020-06-05 11:11:23,957] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=3&pre_page=10 HTTP/1.1" 200 247
[2020-06-05 11:11:28,772] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=ey HTTP/1.1" 200 1803
[2020-06-05 11:11:47,165] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:11:52,229] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=ey HTTP/1.1" 200 1803
[2020-06-05 11:11:56,876] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 1843
[2020-06-05 11:12:11,029] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:12:30,921] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=1&pre_page=10&username=ad HTTP/1.1" 200 0
[2020-06-05 11:12:30,945] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10&username=ad HTTP/1.1" 200 0
[2020-06-05 11:12:30,997] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=ad HTTP/1.1" 200 259
[2020-06-05 11:12:43,242] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 1843
[2020-06-05 11:12:45,804] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=3&pre_page=10 HTTP/1.1" 200 247
[2020-06-05 11:15:01,088] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:15:46,103] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:15:54,568] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=ad HTTP/1.1" 200 259
[2020-06-05 11:16:34,461] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:16:38,245] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=ad HTTP/1.1" 200 259
[2020-06-05 11:16:43,789] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=ey HTTP/1.1" 200 1803
[2020-06-05 11:17:19,063] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:17:19,115] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1459
[2020-06-05 11:17:56,181] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:17:56,197] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 1843
[2020-06-05 11:18:04,487] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=1&pre_page=10&username=d HTTP/1.1" 200 0
[2020-06-05 11:18:04,493] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?current_page=1&pre_page=10&username=d HTTP/1.1" 301 0
[2020-06-05 11:18:04,541] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10&username=d HTTP/1.1" 200 0
[2020-06-05 11:18:04,592] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=d HTTP/1.1" 200 73
[2020-06-05 11:18:06,820] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=ad HTTP/1.1" 200 259
[2020-06-05 11:18:09,947] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=ey HTTP/1.1" 200 1803
[2020-06-05 11:18:13,604] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 1843
[2020-06-05 11:18:15,596] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:18:15,605] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:18:18,137] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=ey HTTP/1.1" 200 1803
[2020-06-05 11:18:20,051] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 1843
[2020-06-05 11:18:21,768] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:18:24,124] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=ey HTTP/1.1" 200 1803
[2020-06-05 11:18:26,902] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 1843
[2020-06-05 11:18:33,348] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=ey HTTP/1.1" 200 1803
[2020-06-05 11:18:35,362] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:18:38,550] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=ey HTTP/1.1" 200 1803
[2020-06-05 11:26:43,924] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:26:43,946] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/&current_page=1&pre_page=10 HTTP/1.1" 301 0
[2020-06-05 11:26:43,992] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/&current_page%3D1&pre_page%3D10/ HTTP/1.1" 200 0
[2020-06-05 11:26:44,047] [log.py:222] [log:log_response] [WARNING]- Not Found: /user/&current_page=1&pre_page=10/
[2020-06-05 11:26:44,049] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /user/&current_page%3D1&pre_page%3D10/ HTTP/1.1" 404 25
[2020-06-05 11:29:21,179] [log.py:222] [log:log_response] [WARNING]- Not Found: /user/&current_page=1&pre_page=10/
[2020-06-05 11:29:21,180] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /user/&current_page%3D1&pre_page%3D10/ HTTP/1.1" 404 25
[2020-06-05 11:29:30,662] [log.py:222] [log:log_response] [WARNING]- Not Found: /user/&current_page=1&pre_page=10/
[2020-06-05 11:29:30,664] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /user/&current_page%3D1&pre_page%3D10/ HTTP/1.1" 404 25
[2020-06-05 11:30:10,511] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:30:10,540] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:31:13,577] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=1&pre_page=10&username=admin HTTP/1.1" 200 0
[2020-06-05 11:31:13,600] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10&username=admin HTTP/1.1" 200 0
[2020-06-05 11:31:13,654] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=admin HTTP/1.1" 200 259
[2020-06-05 11:31:18,148] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=1&pre_page=10&username=e HTTP/1.1" 200 0
[2020-06-05 11:31:18,170] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10&username=e HTTP/1.1" 200 0
[2020-06-05 11:31:18,263] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=e HTTP/1.1" 200 1797
[2020-06-05 11:31:20,906] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?username=e?current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:31:20,918] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e?current_page=2&pre_page=10 HTTP/1.1" 200 2
[2020-06-05 11:34:01,248] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:34:01,260] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?current_page=1&pre_page=10 HTTP/1.1" 301 0
[2020-06-05 11:34:01,314] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:34:04,829] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:34:09,362] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=1&pre_page=10&username=ad HTTP/1.1" 200 0
[2020-06-05 11:34:09,374] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10&username=ad HTTP/1.1" 200 0
[2020-06-05 11:34:09,431] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=ad HTTP/1.1" 200 259
[2020-06-05 11:34:15,420] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10&username=e HTTP/1.1" 200 1797
[2020-06-05 11:34:18,434] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?username=e&current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:34:18,441] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=e&current_page=2&pre_page=10 HTTP/1.1" 301 0
[2020-06-05 11:34:18,487] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?username=e&current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:34:18,538] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=2&pre_page=10 HTTP/1.1" 200 595
[2020-06-05 11:34:21,699] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?username=e&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:34:21,705] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=e&current_page=1&pre_page=10 HTTP/1.1" 301 0
[2020-06-05 11:34:21,752] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?username=e&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:34:21,807] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=1&pre_page=10 HTTP/1.1" 200 1797
[2020-06-05 11:34:22,546] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=2&pre_page=10 HTTP/1.1" 200 595
[2020-06-05 11:34:23,379] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=1&pre_page=10 HTTP/1.1" 200 1797
[2020-06-05 11:34:25,228] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=2&pre_page=10 HTTP/1.1" 200 595
[2020-06-05 11:34:26,303] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=1&pre_page=10 HTTP/1.1" 200 1797
[2020-06-05 11:34:26,945] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=2&pre_page=10 HTTP/1.1" 200 595
[2020-06-05 11:34:27,562] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=1&pre_page=10 HTTP/1.1" 200 1797
[2020-06-05 11:34:28,104] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=2&pre_page=10 HTTP/1.1" 200 595
[2020-06-05 11:34:31,023] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=1&pre_page=10 HTTP/1.1" 200 1797
[2020-06-05 11:34:33,088] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=2&pre_page=10 HTTP/1.1" 200 595
[2020-06-05 11:36:43,559] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:36:52,273] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?username=q&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:36:52,293] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=q&current_page=1&pre_page=10 HTTP/1.1" 301 0
[2020-06-05 11:36:52,344] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?username=q&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:36:52,398] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=q&current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 11:36:56,420] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?username=er&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:36:56,427] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=er&current_page=1&pre_page=10 HTTP/1.1" 301 0
[2020-06-05 11:36:56,477] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?username=er&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:36:56,531] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=er&current_page=1&pre_page=10 HTTP/1.1" 200 240
[2020-06-05 11:37:02,366] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=1&pre_page=10 HTTP/1.1" 200 1797
[2020-06-05 11:37:06,637] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=2&pre_page=10 HTTP/1.1" 200 595
[2020-06-05 11:38:35,440] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:38:38,060] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:38:38,067] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?current_page=2&pre_page=10 HTTP/1.1" 301 0
[2020-06-05 11:38:38,115] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:38:38,170] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 1843
[2020-06-05 11:38:39,120] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=3&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:38:39,127] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?current_page=3&pre_page=10 HTTP/1.1" 301 0
[2020-06-05 11:38:39,173] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=3&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:38:39,220] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=3&pre_page=10 HTTP/1.1" 200 247
[2020-06-05 11:38:42,608] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=1&pre_page=10 HTTP/1.1" 200 1797
[2020-06-05 11:38:45,423] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=2&pre_page=10 HTTP/1.1" 200 595
[2020-06-05 11:38:47,667] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=1&pre_page=10 HTTP/1.1" 200 1797
[2020-06-05 11:38:48,965] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=2&pre_page=10 HTTP/1.1" 200 595
[2020-06-05 11:38:50,107] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=1&pre_page=10 HTTP/1.1" 200 1797
[2020-06-05 11:38:51,102] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=2&pre_page=10 HTTP/1.1" 200 595
[2020-06-05 11:38:51,779] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=e&current_page=1&pre_page=10 HTTP/1.1" 200 1797
[2020-06-05 11:39:57,193] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:40:03,724] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=er&current_page=1&pre_page=10 HTTP/1.1" 200 240
[2020-06-05 11:40:09,836] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?username=ey&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:40:09,840] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=ey&current_page=1&pre_page=10 HTTP/1.1" 301 0
[2020-06-05 11:40:09,885] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?username=ey&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:40:09,934] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ey&current_page=1&pre_page=10 HTTP/1.1" 200 1803
[2020-06-05 11:40:11,927] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?username=ey&current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:40:11,933] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=ey&current_page=2&pre_page=10 HTTP/1.1" 301 0
[2020-06-05 11:40:11,976] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?username=ey&current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:40:12,030] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ey&current_page=2&pre_page=10 HTTP/1.1" 200 421
[2020-06-05 11:40:14,148] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ey&current_page=1&pre_page=10 HTTP/1.1" 200 1803
[2020-06-05 11:40:16,706] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ey&current_page=2&pre_page=10 HTTP/1.1" 200 421
[2020-06-05 11:40:21,866] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:40:21,876] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:40:26,416] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ey&current_page=1&pre_page=10 HTTP/1.1" 200 1803
[2020-06-05 11:40:28,583] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ey&current_page=2&pre_page=10 HTTP/1.1" 200 421
[2020-06-05 11:41:24,377] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:41:27,431] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 1843
[2020-06-05 11:41:33,257] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ey&current_page=1&pre_page=10 HTTP/1.1" 200 1803
[2020-06-05 11:42:15,551] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ey&current_page=2&pre_page=10 HTTP/1.1" 200 421
[2020-06-05 11:42:18,953] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:42:22,734] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=3&pre_page=10 HTTP/1.1" 200 247
[2020-06-05 11:42:28,710] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?username=ad&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:42:28,714] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user?username=ad&current_page=1&pre_page=10 HTTP/1.1" 301 0
[2020-06-05 11:42:28,760] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?username=ad&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:42:28,814] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ad&current_page=1&pre_page=10 HTTP/1.1" 200 259
[2020-06-05 11:47:35,578] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 11:47:36,921] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 11:47:48,897] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 11:47:49,288] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 11:49:06,826] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 11:49:07,186] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 11:49:09,776] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 11:49:09,831] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:49:28,820] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 11:50:01,036] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/ HTTP/1.1" 200 0
[2020-06-05 11:50:01,074] [log.py:222] [log:log_response] [WARNING]- Conflict: /user/
[2020-06-05 11:50:01,075] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /user/ HTTP/1.1" 409 25
[2020-06-05 13:27:54,550] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:27:54,559] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:27:54,630] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:27:55,757] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:27:56,721] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:27:57,040] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:27:57,219] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:27:57,407] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:27:57,566] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:27:57,761] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:27:59,963] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:28:00,587] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:28:00,831] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:28:01,015] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:28:02,213] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:28:08,815] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:28:10,704] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?username=ad&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:28:10,710] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?username=ad&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:28:10,770] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ad&current_page=1&pre_page=10 HTTP/1.1" 200 259
[2020-06-05 13:28:17,317] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?username=er&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:28:17,326] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?username=er&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:28:17,395] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=er&current_page=1&pre_page=10 HTTP/1.1" 200 240
[2020-06-05 13:28:20,235] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?username=ey&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:28:20,246] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?username=ey&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:28:20,320] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ey&current_page=1&pre_page=10 HTTP/1.1" 200 1803
[2020-06-05 13:28:27,970] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?username=ey&current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:28:27,977] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?username=ey&current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:28:28,026] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ey&current_page=2&pre_page=10 HTTP/1.1" 200 421
[2020-06-05 13:28:51,137] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:29:06,509] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:29:07,461] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:29:07,983] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:29:08,171] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:29:08,391] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:29:08,600] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:29:08,765] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:29:09,007] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:29:09,258] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:29:09,728] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:29:10,118] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:29:13,268] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:29:27,639] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:29:27,645] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:29:27,707] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=2&pre_page=10 HTTP/1.1" 200 1843
[2020-06-05 13:29:28,492] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user?current_page=3&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:29:28,498] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=3&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:29:28,560] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=3&pre_page=10 HTTP/1.1" 200 247
[2020-06-05 13:29:30,187] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:30:05,965] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ey&current_page=1&pre_page=10 HTTP/1.1" 200 1803
[2020-06-05 13:30:11,910] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ey&current_page=2&pre_page=10 HTTP/1.1" 200 421
[2020-06-05 13:30:46,589] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:30:56,374] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ey&current_page=1&pre_page=10 HTTP/1.1" 200 1803
[2020-06-05 13:30:59,695] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?username=ey&current_page=2&pre_page=10 HTTP/1.1" 200 421
[2020-06-05 13:31:56,840] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:32:30,581] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/ HTTP/1.1" 200 0
[2020-06-05 13:32:30,604] [log.py:222] [log:log_response] [WARNING]- Conflict: /user/
[2020-06-05 13:32:30,605] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /user/ HTTP/1.1" 409 25
[2020-06-05 13:33:26,324] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:33:38,010] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:34:02,218] [log.py:222] [log:log_response] [WARNING]- Conflict: /user/
[2020-06-05 13:34:02,219] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /user/ HTTP/1.1" 409 25
[2020-06-05 13:34:55,920] [log.py:222] [log:log_response] [WARNING]- Conflict: /user/
[2020-06-05 13:34:55,922] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /user/ HTTP/1.1" 409 25
[2020-06-05 13:35:00,702] [log.py:222] [log:log_response] [WARNING]- Conflict: /user/
[2020-06-05 13:35:00,702] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /user/ HTTP/1.1" 409 25
[2020-06-05 13:35:04,650] [log.py:222] [log:log_response] [WARNING]- Bad Request: /user/
[2020-06-05 13:35:04,650] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /user/ HTTP/1.1" 400 47
[2020-06-05 13:41:23,952] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:41:23,976] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 1837
[2020-06-05 13:41:26,386] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:41:26,431] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1459
[2020-06-05 13:41:39,470] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/ HTTP/1.1" 200 0
[2020-06-05 13:41:39,616] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 137
[2020-06-05 13:41:47,966] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?name=yxt&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:41:48,016] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=yxt&current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:41:50,469] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=yxt&current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:43:51,400] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 13:43:51,739] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 13:43:54,666] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /role/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 454, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 94, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'User' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 244, in list
    data = self.get_serializer(result, many=True).data
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 760, in data
    ret = super().data
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 677, in to_representation
    return [
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 678, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 516, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 487, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `name` on serializer `RoleSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `User` instance.
Original exception text was: 'User' object has no attribute 'name'.
[2020-06-05 13:43:54,668] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 500 21495
[2020-06-05 13:43:58,750] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /role/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 454, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 94, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'User' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 244, in list
    data = self.get_serializer(result, many=True).data
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 760, in data
    ret = super().data
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 677, in to_representation
    return [
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 678, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 516, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 487, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `name` on serializer `RoleSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `User` instance.
Original exception text was: 'User' object has no attribute 'name'.
[2020-06-05 13:43:58,753] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 500 21495
[2020-06-05 13:44:06,731] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /role/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 454, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 94, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'User' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 244, in list
    data = self.get_serializer(result, many=True).data
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 760, in data
    ret = super().data
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 677, in to_representation
    return [
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 678, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 516, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 487, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `name` on serializer `RoleSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `User` instance.
Original exception text was: 'User' object has no attribute 'name'.
[2020-06-05 13:44:06,734] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 500 21495
[2020-06-05 13:44:33,802] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 13:44:34,210] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 13:44:37,559] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /role/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 454, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 94, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'User' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 244, in list
    data = self.get_serializer(result, many=True).data
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 760, in data
    ret = super().data
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 677, in to_representation
    return [
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 678, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 516, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 487, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `name` on serializer `RoleSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `User` instance.
Original exception text was: 'User' object has no attribute 'name'.
[2020-06-05 13:44:37,561] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 500 21495
[2020-06-05 13:44:44,068] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /role/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 454, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 94, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'User' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 244, in list
    data = self.get_serializer(result, many=True).data
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 760, in data
    ret = super().data
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 677, in to_representation
    return [
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 678, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 516, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 487, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `name` on serializer `RoleSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `User` instance.
Original exception text was: 'User' object has no attribute 'name'.
[2020-06-05 13:44:44,073] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 500 21495
[2020-06-05 13:45:04,973] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py changed, reloading.
[2020-06-05 13:45:05,282] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 13:45:08,553] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:45:33,702] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:45:44,516] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?name=ad&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:45:44,542] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=ad&current_page=1&pre_page=10 HTTP/1.1" 200 707
[2020-06-05 13:45:47,375] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?name=a&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:45:47,400] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=a&current_page=1&pre_page=10 HTTP/1.1" 200 707
[2020-06-05 13:45:52,805] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?name=a%20&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:45:52,819] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=a%20&current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 13:45:54,977] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:46:10,507] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 13:46:10,508] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 13:47:04,496] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:47:06,880] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:47:15,285] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 13:47:15,286] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 13:47:38,332] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:47:41,418] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:47:51,550] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 13:47:51,550] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 13:48:14,405] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:48:16,303] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:48:27,044] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 13:48:27,044] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 13:48:51,188] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:48:53,322] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:49:05,528] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 13:49:05,529] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 13:50:31,760] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:50:40,345] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:50:49,847] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:51:01,877] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 13:51:01,879] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 13:52:48,865] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 13:52:48,911] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:55:20,661] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 13:55:35,330] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 14:06:09,109] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 14:06:09,155] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1597
[2020-06-05 14:06:22,944] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/ HTTP/1.1" 200 0
[2020-06-05 14:06:23,003] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 137
[2020-06-05 14:06:23,117] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1735
[2020-06-05 14:08:58,470] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1735
[2020-06-05 14:09:09,399] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:09:09,400] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:09:23,335] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:09:23,336] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:09:58,097] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1735
[2020-06-05 14:10:01,359] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1735
[2020-06-05 14:10:13,565] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 137
[2020-06-05 14:10:13,644] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:12:58,973] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:13:15,574] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:13:20,806] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:13:34,833] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:13:34,834] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:15:58,626] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:15:58,627] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:18:32,413] [log.py:222] [log:log_response] [WARNING]- Forbidden: /role/
[2020-06-05 14:18:32,414] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 403 40
[2020-06-05 14:18:53,359] [log.py:222] [log:log_response] [WARNING]- Bad Request: /role/
[2020-06-05 14:18:53,360] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 400 73
[2020-06-05 14:19:14,431] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:19:14,432] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:20:37,182] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 14:20:37,254] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:20:40,338] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:20:58,716] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/ HTTP/1.1" 200 0
[2020-06-05 14:20:58,731] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:20:58,732] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:22:02,094] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:22:14,342] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:22:14,344] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:24:16,084] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:24:22,942] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:24:32,655] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:24:51,010] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:24:51,011] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:24:54,264] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:24:54,265] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:24:55,063] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:24:55,064] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:24:55,447] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:24:55,448] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:24:55,696] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:24:55,697] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:24:55,998] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:24:55,999] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:25:41,417] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:25:41,418] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:26:09,887] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:26:11,715] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:26:20,795] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:26:20,796] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:26:49,455] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:26:51,458] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:27:04,192] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:27:06,193] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:27:15,079] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:27:15,081] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:27:21,280] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:27:21,280] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:28:24,574] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:28:26,940] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 1873
[2020-06-05 14:28:33,320] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 136
[2020-06-05 14:28:49,569] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 2010
[2020-06-05 14:28:49,955] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 2010
[2020-06-05 14:28:57,281] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 137
[2020-06-05 14:29:08,753] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 2148
[2020-06-05 14:29:09,080] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 2148
[2020-06-05 14:29:17,046] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 138
[2020-06-05 14:29:32,328] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 2288
[2020-06-05 14:31:55,512] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 14:31:55,593] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 2288
[2020-06-05 14:32:03,194] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/ HTTP/1.1" 200 0
[2020-06-05 14:32:03,204] [log.py:222] [log:log_response] [WARNING]- Conflict: /role/
[2020-06-05 14:32:03,204] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /role/ HTTP/1.1" 409 25
[2020-06-05 14:34:17,438] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 2288
[2020-06-05 14:34:28,286] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 2288
[2020-06-05 14:34:42,379] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 138
[2020-06-05 14:34:42,440] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 2288
[2020-06-05 14:34:46,680] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?name=w&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 14:34:46,716] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=w&current_page=1&pre_page=10 HTTP/1.1" 200 763
[2020-06-05 14:34:54,525] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 140
[2020-06-05 14:34:54,571] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=w&current_page=1&pre_page=10 HTTP/1.1" 200 904
[2020-06-05 14:34:58,943] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 144
[2020-06-05 14:34:59,001] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=w&current_page=1&pre_page=10 HTTP/1.1" 200 1049
[2020-06-05 14:35:03,980] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 145
[2020-06-05 14:35:04,023] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=w&current_page=1&pre_page=10 HTTP/1.1" 200 1195
[2020-06-05 14:35:09,739] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 142
[2020-06-05 14:35:09,805] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=w&current_page=1&pre_page=10 HTTP/1.1" 200 1338
[2020-06-05 14:35:14,782] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 141
[2020-06-05 14:35:14,852] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=w&current_page=1&pre_page=10 HTTP/1.1" 200 1481
[2020-06-05 14:35:21,167] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 143
[2020-06-05 14:35:21,226] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=w&current_page=1&pre_page=10 HTTP/1.1" 200 1481
[2020-06-05 14:35:24,983] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=w&current_page=1&pre_page=10 HTTP/1.1" 200 1481
[2020-06-05 14:35:26,875] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?name=w&current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 14:35:26,889] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=w&current_page=2&pre_page=10 HTTP/1.1" 200 217
[2020-06-05 14:35:28,874] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=w&current_page=1&pre_page=10 HTTP/1.1" 200 1481
[2020-06-05 14:35:32,802] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=w&current_page=1&pre_page=10 HTTP/1.1" 200 1481
[2020-06-05 14:35:36,768] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?name=m&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 14:35:36,788] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=m&current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 14:35:42,231] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?name=%E9%A9%AC%E5%88%A9%E5%BC%BA&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 14:35:42,265] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=%E9%A9%AC%E5%88%A9%E5%BC%BA&current_page=1&pre_page=10 HTTP/1.1" 200 548
[2020-06-05 14:35:44,950] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?name=%E9%A9%AC%E5%88%A9&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 14:35:44,988] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=%E9%A9%AC%E5%88%A9&current_page=1&pre_page=10 HTTP/1.1" 200 548
[2020-06-05 14:35:47,766] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?name=%E9%A9%AC&current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 14:35:47,795] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?name=%E9%A9%AC&current_page=1&pre_page=10 HTTP/1.1" 200 548
[2020-06-05 14:35:50,339] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 2288
[2020-06-05 14:35:53,254] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 2288
[2020-06-05 14:35:55,012] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?current_page=2&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 14:35:55,059] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=2&pre_page=10 HTTP/1.1" 200 1073
[2020-06-05 14:35:56,901] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 2288
[2020-06-05 14:36:05,135] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 14:36:05,156] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 380
[2020-06-05 14:45:49,821] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/models.py changed, reloading.
[2020-06-05 14:45:50,303] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 14:46:42,818] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/models.py changed, reloading.
[2020-06-05 14:46:43,138] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 14:47:06,435] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/models.py changed, reloading.
[2020-06-05 14:47:06,782] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 15:03:35,240] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 15:03:41,300] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 15:03:41,316] [log.py:222] [log:log_response] [WARNING]- Forbidden: /menu/
[2020-06-05 15:03:41,316] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 403 40
[2020-06-05 15:03:53,573] [log.py:222] [log:log_response] [WARNING]- Forbidden: /menu/
[2020-06-05 15:03:53,574] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 403 40
[2020-06-05 15:04:06,858] [log.py:222] [log:log_response] [WARNING]- Forbidden: /menu/
[2020-06-05 15:04:06,858] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 403 40
[2020-06-05 15:04:18,763] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 15:04:18,775] [log.py:222] [log:log_response] [WARNING]- Forbidden: /user/
[2020-06-05 15:04:18,776] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 403 40
[2020-06-05 15:04:51,219] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 15:04:51,230] [log.py:222] [log:log_response] [WARNING]- Forbidden: /role/
[2020-06-05 15:04:51,231] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 403 40
[2020-06-05 15:05:07,282] [log.py:222] [log:log_response] [WARNING]- Forbidden: /user/
[2020-06-05 15:05:07,282] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 403 40
[2020-06-05 15:05:17,093] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /auth/ HTTP/1.1" 200 0
[2020-06-05 15:05:17,350] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /auth/
Traceback (most recent call last):
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 95, in post
    raise exceptions.AuthenticationFailed('未查询到用户信息！')
rest_framework.exceptions.AuthenticationFailed: 未查询到用户信息！

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 105, in post
    except exceptions as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
[2020-06-05 15:05:17,351] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /auth/ HTTP/1.1" 500 19876
[2020-06-05 15:05:50,667] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /auth/
Traceback (most recent call last):
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 95, in post
    raise exceptions.AuthenticationFailed('未查询到用户信息！')
rest_framework.exceptions.AuthenticationFailed: 未查询到用户信息！

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 105, in post
    except exceptions as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
[2020-06-05 15:05:50,668] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /auth/ HTTP/1.1" 500 19876
[2020-06-05 15:06:21,740] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 15:07:02,279] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /auth/
Traceback (most recent call last):
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 95, in post
    raise exceptions.AuthenticationFailed('未查询到用户信息！')
rest_framework.exceptions.AuthenticationFailed: 未查询到用户信息！

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/quality_inspection/python-workspace/project-sys/sys_auth/views.py", line 105, in post
    except exceptions as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
[2020-06-05 15:07:02,280] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /auth/ HTTP/1.1" 500 19876
[2020-06-05 15:08:38,175] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /auth/ HTTP/1.1" 200 65
[2020-06-05 15:08:42,856] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 242
[2020-06-05 15:08:44,026] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:08:44,997] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:09:36,787] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/ HTTP/1.1" 200 0
[2020-06-05 15:09:36,865] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 173
[2020-06-05 15:09:36,932] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 416
[2020-06-05 15:10:07,978] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /user/ HTTP/1.1" 201 175
[2020-06-05 15:10:08,005] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 592
[2020-06-05 15:11:25,564] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/ HTTP/1.1" 200 0
[2020-06-05 15:11:25,645] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 139
[2020-06-05 15:11:25,724] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 212
[2020-06-05 15:11:35,077] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 138
[2020-06-05 15:11:35,102] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 351
[2020-06-05 15:11:52,207] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /role/ HTTP/1.1" 201 140
[2020-06-05 15:11:52,258] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 492
[2020-06-05 15:12:47,441] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:13:35,460] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:18:48,079] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 15:18:48,097] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:19:38,985] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:23:49,506] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:23:53,368] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:26:50,045] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 15:26:50,061] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 592
[2020-06-05 15:26:54,243] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 15:26:54,280] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 492
[2020-06-05 15:27:39,688] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/ HTTP/1.1" 200 0
[2020-06-05 15:27:39,701] [log.py:222] [log:log_response] [WARNING]- Bad Request: /menu/
[2020-06-05 15:27:39,702] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /menu/ HTTP/1.1" 400 163
[2020-06-05 15:28:15,876] [log.py:222] [log:log_response] [WARNING]- Bad Request: /menu/
[2020-06-05 15:28:15,877] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /menu/ HTTP/1.1" 400 120
[2020-06-05 15:31:49,204] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 15:31:49,236] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:31:51,858] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:32:31,759] [log.py:222] [log:log_response] [WARNING]- Bad Request: /menu/
[2020-06-05 15:32:31,760] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /menu/ HTTP/1.1" 400 120
[2020-06-05 15:35:27,626] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:35:52,730] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:36:38,556] [log.py:222] [log:log_response] [WARNING]- Bad Request: /menu/
[2020-06-05 15:36:38,557] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /menu/ HTTP/1.1" 400 84
[2020-06-05 15:37:51,871] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/ HTTP/1.1" 200 0
[2020-06-05 15:37:51,884] [log.py:222] [log:log_response] [WARNING]- Bad Request: /menu/
[2020-06-05 15:37:51,884] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /menu/ HTTP/1.1" 400 44
[2020-06-05 15:41:39,115] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/models.py changed, reloading.
[2020-06-05 15:41:39,505] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 15:47:26,647] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 15:47:31,361] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 15:47:31,398] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:47:46,586] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:47:53,376] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:48:37,637] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:48:39,607] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:49:09,703] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/ HTTP/1.1" 200 0
[2020-06-05 15:49:09,954] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /menu/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1048, "Column 'pre_menu' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 948, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/base.py", line 782, in save_base
    updated = self._save_table(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/base.py", line 924, in _do_insert
    return manager._insert(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1391, in execute_sql
    cursor.execute(sql, params)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 79, in execute
    raise utils.IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'pre_menu' cannot be null")
[2020-06-05 15:49:09,959] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /menu/ HTTP/1.1" 500 23209
[2020-06-05 15:50:31,325] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/models.py changed, reloading.
[2020-06-05 15:50:31,748] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 15:52:53,790] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/models.py changed, reloading.
[2020-06-05 15:52:54,180] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 15:53:04,785] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- /home/rock/quality_inspection/python-workspace/project-sys/sys_auth/models.py changed, reloading.
[2020-06-05 15:53:05,232] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 15:57:41,224] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 15:57:47,304] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 15:57:47,339] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:57:57,442] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:58:07,290] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 15:58:46,157] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /menu/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'prev_menu' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 948, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/base.py", line 782, in save_base
    updated = self._save_table(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/base.py", line 924, in _do_insert
    return manager._insert(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1391, in execute_sql
    cursor.execute(sql, params)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'prev_menu' in 'field list'")
[2020-06-05 15:58:46,160] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /menu/ HTTP/1.1" 500 24163
[2020-06-05 16:12:01,884] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-06-05 16:12:09,844] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 16:12:09,874] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 16:12:21,821] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 73
[2020-06-05 16:12:58,472] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/ HTTP/1.1" 200 0
[2020-06-05 16:12:58,538] [log.py:222] [log:log_response] [ERROR]- Internal Server Error: /menu/
Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1048, "Column 'prev_menu' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 948, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/base.py", line 782, in save_base
    updated = self._save_table(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/base.py", line 924, in _do_insert
    return manager._insert(
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1391, in execute_sql
    cursor.execute(sql, params)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rock/anaconda3/envs/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 79, in execute
    raise utils.IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'prev_menu' cannot be null")
[2020-06-05 16:12:58,541] [basehttp.py:157] [basehttp:log_message] [ERROR]- "POST /menu/ HTTP/1.1" 500 23223
[2020-06-05 16:13:20,661] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /menu/ HTTP/1.1" 201 209
[2020-06-05 16:13:20,703] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 282
[2020-06-05 16:13:23,509] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 282
[2020-06-05 16:14:05,486] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /menu/ HTTP/1.1" 201 195
[2020-06-05 16:14:05,586] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 478
[2020-06-05 16:14:07,134] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 16:14:07,159] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 492
[2020-06-05 16:14:09,680] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 16:14:09,698] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 592
[2020-06-05 16:14:33,445] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /menu/ HTTP/1.1" 201 195
[2020-06-05 16:14:33,483] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 674
[2020-06-05 16:15:19,028] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /menu/ HTTP/1.1" 201 195
[2020-06-05 16:15:19,128] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 870
[2020-06-05 16:16:00,464] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/4/ HTTP/1.1" 200 0
[2020-06-05 16:16:00,541] [basehttp.py:157] [basehttp:log_message] [INFO]- "PUT /menu/4/ HTTP/1.1" 200 196
[2020-06-05 16:16:29,370] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/3/ HTTP/1.1" 200 0
[2020-06-05 16:16:29,445] [basehttp.py:157] [basehttp:log_message] [INFO]- "PUT /menu/3/ HTTP/1.1" 200 196
[2020-06-05 16:28:10,866] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 16:28:10,885] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 872
[2020-06-05 16:36:20,523] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 872
[2020-06-05 16:41:07,449] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 16:41:07,490] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 872
[2020-06-05 16:56:54,283] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 16:56:54,309] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 872
[2020-06-05 16:58:04,156] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 872
[2020-06-05 16:58:32,742] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 872
[2020-06-05 17:03:01,657] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 872
[2020-06-05 17:03:46,995] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 872
[2020-06-05 17:04:43,080] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 872
[2020-06-05 17:06:27,464] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 872
[2020-06-05 17:08:25,135] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 17:08:25,163] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 872
[2020-06-05 17:09:19,770] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 872
[2020-06-05 17:10:33,784] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 872
[2020-06-05 17:32:35,354] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /user/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 17:32:35,381] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /user/?current_page=1&pre_page=10 HTTP/1.1" 200 592
[2020-06-05 17:32:36,548] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /role/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 17:32:36,583] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /role/?current_page=1&pre_page=10 HTTP/1.1" 200 492
[2020-06-05 17:32:39,795] [basehttp.py:157] [basehttp:log_message] [INFO]- "OPTIONS /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 0
[2020-06-05 17:32:39,813] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /menu/?current_page=1&pre_page=10 HTTP/1.1" 200 872
